---
- name: "Spin up TeamCity ec2 instance"
  ec2:
    key_name: ai-apphost
    instance_type: "{{ instance_type }}"
    image: "{{ instance_ami }}"
    wait: true
    group: no_security_at_all
    count: 1
    vpc_subnet_id: subnet-f2011596
    region: ap-southeast-2
    assign_public_ip: yes
    count_tag:
      Name: "{{ teamcity_agent_name }}"
    instance_tags:
      Name: "{{ teamcity_agent_name }}"
    user_data: "{{ lookup('template', 'userdata.j2') }}"
  register: ec2

- debug:
    msg: "Instance {{ item.id }} created successfully."
  with_items: "{{ ec2.instances }}"

- name: "Add the instance to host group: {{ teamcity_agent_name }}"
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: win
  with_items: "{{ ec2.instances }}"

- name: wait for WinRM to answer
  wait_for:
    port: 5986
    host: "{{ item.public_ip }}"
    timeout: 300
  with_items: "{{ ec2.instances }}"
